### ISSUE TITLE
Support model binder

### ISSUE THREAD

**Issue by redplane** [redplane/ApiMultipartFormFormatter#10]
Model binder on view model properties should be supported.

**Comment by RudeySH** [comment]
The readme currently says:

> From version 3.0.0, this plugin uses IModelBinderService to serialize data read from MultipartFormDataContent stream

Does that mean that model binding is currently supported?

**Comment by redplane** [comment]
Yes, you can refer to these binder services [here](https://github.com/redplane/ApiMultipartFormFormatter/tree/master/lib/ApiMultipartFormDataFormatter/Services/Implementations).

In the document, I already metioned how to implement those binder while registering this formatter.
