### ISSUE TITLE
Nuget 3.0 release ETA

### ISSUE THREAD

**Issue by gthieme** [redplane/ApiMultipartFormFormatter#12]
When you to think a final Nuget release will be cut for 3.0?

I'm very excited about using ApiMultipartFormFormatter because I need Stream support for file uploads. The problem is that my company's CI (Continuous Integration) server always fails to build because it doesn't accept preview versions of Nuget packages.

Thanks,
Geoff

**Comment by redplane** [comment]
A new version is being updated to support `Net Core 2.2`, `Net Core 3.0` and `Net Core 3.1`.
For now, the progress is:
- **Completed** unit testing
- **Doing** integration testing with Test Server.

It can be found [here](https://github.com/redplane/ApiMultipartFormFormatter/tree/feature/netcore-support).

My ETA for this is about 1 week to complete integration tests & publishing the nuget package :).

**Comment by gthieme** [comment]
Will this new release still support .net deployments using old IIS servers? I'm still stuck on Visual Studio 2015 at my company, so I can't use .net core.

Did you fix any out of memory issues when processing large files (like 300MB or 2 GB)? I tried using 3.0.0-Preview-001 to stream a large file and it failed with "Error writing MIME multipart body part to output stream." caused by an OutOfMemoryException. I was using a HttpFileBase read using new StreamContent(myObject.myHttpFileBase.InputStream).

I was able to successfully stream that same file using HttpContext.Current.Request.GetBufferedInputStream() in my rest web api service. Hardly any memory IIS memory was used when chunk streaming a 300MB file. I had to use Transfer-Encoding:Chunked in my Postman request. My IIS service then had to stream the data to another 3rd party rest service using request.Headers.TransferEncodingChunked=true.

Thanks, 
Geoff

**Comment by redplane** [comment]
@gthieme , 
Of course, old version of IIS is supported (.Net Framework actually).
About file streaming, for now it is suggested using smaller file first, about large file, for now I dont have a proper solution for it. A reproduction will be welcome.

>I had to use Transfer-Encoding:Chunked in my Postman request. My IIS service then had to stream the data to another 3rd party rest service using request.Headers.TransferEncodingChunked=true.

I'll think about this kind of solution and try to apply to this library :)

**Comment by redplane** [comment]
Now, the release candidate version `3.0.0` has been released on Nuget package.
It supports both .Net Framework (>= 4.5.2) and Net Core (2.2.0).

I'll close this issue, if you face with any further problems, please feel free to open the new one :).
