### ISSUE TITLE
MultipartFormDataFormatter is not compatible with HttpClient in Asp .Net Core 3.1

### ISSUE THREAD

**Issue by mr-fedorof** [redplane/ApiMultipartFormFormatter#14]
MultipartFormDataFormatter is not compatible with HttpClient in Asp .Net Core 3.1
```C#
var HttpClient = new HttpClient();
var httpResponse = await HttpClient.GetAsync("http://localhost/content");
var data = await httpResponse.Content.ReadAsAsync<T>(/* The argument expects IEnumerable<MediaTypeFormatter> */);
```
But **MultipartFormDataFormatter** inherits from **InputFormatter**.

Could you make some changes to support http clients?

**Comment by redplane** [comment]
`MultipartFormDataFormatter` is a serializer for `ASP.Net Core` hosting.
As I understand, you want to download the binary from ASP.Net Core Web API, am I right ?

**Comment by mr-fedorof** [comment]
Yes, I would like to download multipart/form-data and bind it to any entity like it's used in model binding in controllers.
As such model, for instance:
```C#
public class Response {
    public IFormFile Data { get; set; }
    public PropertiesClass Properties { get; set; }
}
```

**Comment by redplane** [comment]
@mr-fedorof , this library is for **Uploading** purpose only. Which means, it only has responsibility to handle data **POSTED** from client to api and bind to a `ViewModel` only.

If you want to download the file from your server, you should follow [this tutorial](https://stackoverflow.com/questions/307688/how-to-download-a-file-from-a-url-in-c)

**Comment by redplane** [comment]
I'll close this issue because it seems to be about downloading binary data, which is out of this module's scope.
@mr-fedorof , if you are still facing any problems while downloading binary data, you can create another issue for the demo request.
