### ISSUE TITLE
HttpFile cannot be null

### ISSUE THREAD

**Issue by ivan-srsen** [redplane/ApiMultipartFormFormatter#16]

**Comment by redplane** [comment]
@ivan-srsen , can you provide more information about this issue ? especially how to re-produce this ?

**Comment by ivan-srsen** [comment]
@redplane ASP.NET Web Api, the exception is thrown if you have HttpFile property inside DTO, but you don't send it via ajax call (it's empty). It says 'unexpected end of mime multipart stream'.

**Comment by redplane** [comment]
Is the **DTO** for receiving data from browser client ?
Can you show me some codes please ?

**Comment by ivan-srsen** [comment]
Yes, it's JQuery client.

`$.ajax({
url: "/api/products",
method: POST,
dataType: 'json',
data: getFormData(),
processData: false,
contentType: false,
success: function(){
},
error: function(er) {
}
});`

`function getFormData() {
var jsonObject = JSON.stringify(getPObject());
var formData = new FormData();
formData.append("jsonData", jsonObject);
formData.append("MapShapeFile", shapeFileInput[0].files[0]);
formData.append("MapDbfFile", dbfFileInput[0].files[0]);

return formData;
}`

**Comment by redplane** [comment]
@ivan-srsen , I have re-produced your issue.
However, the parameter can be mapped correctly as the image below:

- The client code:
```
$('#attachmentPicker').change(function () {
	console.log($('#attachmentPicker')[0]);
	var attachmentPickerControl = $('#attachmentPicker')[0];
	var attachments = attachmentPickerControl.files;

	if (!attachments || attachments.length < 1) {
		return;
	}

	var attachment = attachments[0];

	var formData = new FormData();
	formData.append('attachment', attachment);

	$.ajax({
		url: "http://localhost:51506/api/upload",
		method: 'POST',
		dataType: 'json',
		data: formData,
		processData: false,
		contentType: false,
		success: function () { },
		error: function (er) { }
	});
});
```

- The result in API controller:

![image](https://user-images.githubusercontent.com/7974095/116857943-d0b29a80-ac27-11eb-93d8-6745d4b6ffb1.png)

The example I am working on can be found [here](https://github.com/redplane/ApiMultipartFormFormatter/pull/new/fix/issue-16).

If the issue still happens, I need your help to reproduce the issue on a Github repository for better debugging.

**Comment by redplane** [comment]
I'll close this issue for now due to no response.
Please feel free to open this back if the issue still happens.
