### ISSUE TITLE
streaming support

### ISSUE THREAD

**Issue by Driedas** [redplane/ApiMultipartFormFormatter#5]
Hey,
appreciate the work done on this project, had to slightly change it locally to switch from using byte[] to streaming on the HttpFile class (not a fan of reading files into byte[] for potentially large files).
Would you consider a pull request adding support for streaming in addition of just a byte array on the HttpFile class?
At a glance, maybe something like a StreamingHttpFile class with a Stream property instead of byte[] and in the MultipartFormDataFormatter class right before HttpFile is instantiated check what type the property on the model is (HttpFile or StreamingHttpFile) and based on that instantiate one or the other, reading in the byte array or the stream associated with the file, respectively.

**Comment by redplane** [comment]
Yes, please do a PR, we can do it together :)

**Comment by redplane** [comment]
Request has been merged into *rc-3.0.0* and *release-3.0.0*.
Closed for now. Any issue please create a new one.
