### ISSUE TITLE
Dependency Issue?

### ISSUE THREAD

**Issue by joshua-kissinger** [redplane/ApiMultipartFormFormatter#8]
Thanks for the work on this - it appears to be a useful library. When I try to utilize, I get the error below. I don't claim to be an expert on this, but does that mean you have a dependency on Microsoft.AspNet.WebApi.Client >= 5.2.6.0 also? 

Assembly 'ApiMultiPartFormData' with identity 'ApiMultiPartFormData, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' uses 'System.Net.Http.Formatting, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Net.Http.Formatting' with identity 'System.Net.Http.Formatting, Version=5.2.4.0

**Comment by redplane** [comment]
Sorry for my late reply. Can you post an example project here ?

**Comment by joshua-kissinger** [comment]
I think this can be recreated by changing your package.config to utilize WebApi v5.2.3, like Nuget file dictates. Based on your package.config, it does look like you actually use higher versions to build the project. I only noticed because v5.2.3 was in our internal repository, but v5.2.6 isn't. I'm guessing that your project won't compile if you actually use the versions in your nuspec file.

From your package.config
```
<package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net45" developmentDependency="true"  />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.6" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.6" targetFramework="net45" developmentDependency="true" />
```

From nuget/nuspec:
Microsoft.AspNet.WebApi.Client (>= 5.2.3)
Microsoft.AspNet.WebApi.Core (>= 5.2.3)

**Comment by redplane** [comment]
Please try the [latest version](https://www.nuget.org/packages/ApiMultipartFormDataFormatter/2.1.0).
I already downgraded the dependencies to version of 5.2.2.
